### ISSUE TITLE
RTSP & rotation

### ISSUE THREAD

**Issue by thomasbidou** [info-beamer/package-mjpeg-viewer#1]
Hi,

Is there any way to have RTSP cameras on?
And to rotate the screen?

Regards,

**Comment by dividuum** [comment]
No. This package is only for MJPEG streams. It does not allow RTSP. See https://community.info-beamer.com/t/multiple-rtsp-streams/1075/4 for a way to show RTSP streams. The mentioned package also supports rotating the screen.
